jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:buildx-stable-1
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.prod
          platforms: linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/blog-app:${{ github.ref_name }}
            ${{ vars.DOCKERHUB_USERNAME }}/blog-app:latest
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/blog-app:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/blog-app:buildcache,mode=max
