name: Rails Tests
#asdfasdfasd

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: blog_app_test
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/blog_app_test

    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Setup DB
        run: |
          RAILS_ENV=test bin/rails db:environment:set
          RAILS_ENV=test bin/rails db:schema:load

      - name: Run tests
        run: bundle exec rails test test/models/post_test.rb

